### ISSUE TITLE
.\Whitelist.csv - Specified path is neither a file, nor a directory.

### ISSUE THREAD

**Issue by pkoepke** [nexus-prime/QuickMag.jl#1]
I downloaded the code and ran it in Windows 10 by double-clicking Start_Win.bat. Everything worked until:

`julia version 1.6.1
Starting QuickMag

Updating dependencies...
    Updating registry at `C:\Users\paulk\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\paulk\.julia\environments\v1.6\Manifest.toml`

Checking database status...
No database found. Building new database of BOINC hosts:
Reading .\WhiteList.csv
ERROR: LoadError: LoadError: ArgumentError: Specified path is neither a file, nor a directory.
Stacktrace:
 [1] _loadtable(T::Type, files::String; chunks::Nothing, output::Nothing, append::Bool, indexcols::Vector{Any}, distributed::Bool, usecache::Bool, opts::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ JuliaDB C:\Users\paulk\.julia\packages\JuliaDB\Ve2iH\src\io.jl:101
 [2] _loadtable
   @ C:\Users\paulk\.julia\packages\JuliaDB\Ve2iH\src\io.jl:95 [inlined]
 [3] #loadtable#186
   @ C:\Users\paulk\.julia\packages\JuliaDB\Ve2iH\src\io.jl:63 [inlined]
 [4] loadtable(files::String)
   @ JuliaDB C:\Users\paulk\.julia\packages\JuliaDB\Ve2iH\src\io.jl:63
 [5] top-level scope
   @ C:\Users\paulk\Downloads\QuickMag.jl-main\src\updateDatabase.jl:121
 [6] include(fname::String)
   @ Base.MainInclude .\client.jl:444
 [7] top-level scope
   @ C:\Users\paulk\Downloads\QuickMag.jl-main\Run_QuickMag.jl:44
in expression starting at C:\Users\paulk\Downloads\QuickMag.jl-main\src\updateDatabase.jl:121
in expression starting at C:\Users\paulk\Downloads\QuickMag.jl-main\Run_QuickMag.jl:17
Press any key to continue . . .`

**Comment by nexus-prime** [comment]
Do you have WhiteList.csv in the  same directory as Start_Win.bat and Run_QuickMag.jl?

**Comment by pkoepke** [comment]
I don't - README.md doesn't say anything about getting WhiteList.csv first, it just says:

> After starting the program, just follow the instructions in the terminal.

I can try again if you'll tell me where to get WhiteList.csv from. Thanks!

**Comment by nexus-prime** [comment]
You need the full GitHub directory.
I'll clarify in the README.txt

**Comment by nexus-prime** [comment]
Oh, I forgot to add the WhiteList.csv to the GitHub repo...
Just add the csv file to the same directory as Run_QuickMag.jl

**Comment by pkoepke** [comment]
I deleted the directory and downloaded the whole project again. Looks like it got just a bit farther before hitting an error. Want me to start a new issue for this or just use this one?

`Reading .\WhiteList.csv
The system cannot find the file specified.
ERROR: LoadError: LoadError: failed process: Process(`cmd /C rmdir /Q /S 'C:\Users\paulk\Downloads\QuickMag.jl-main\HostFiles'`, ProcessExited(2)) [2]

Stacktrace:
 [1] pipeline_error
   @ .\process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base .\process.jl:440
 [3] run(::Cmd)
   @ Base .\process.jl:438
 [4] top-level scope
   @ C:\Users\paulk\Downloads\QuickMag.jl-main\src\updateDatabase.jl:128
 [5] include(fname::String)
   @ Base.MainInclude .\client.jl:444
 [6] top-level scope
   @ C:\Users\paulk\Downloads\QuickMag.jl-main\Run_QuickMag.jl:44
in expression starting at C:\Users\paulk\Downloads\QuickMag.jl-main\src\updateDatabase.jl:127
in expression starting at C:\Users\paulk\Downloads\QuickMag.jl-main\Run_QuickMag.jl:17
Press any key to continue . . .`

**Comment by nexus-prime** [comment]
start a new issue
