### ISSUE TITLE
quickmag reports mag for asteroids on a RX570 but asteroids website shows no GPU tasks reported

### ISSUE THREAD

**Issue by actng** [nexus-prime/QuickMag.jl#10]
Asteroids site showing no AMD GPU tasks reported
https://asteroidsathome.net/boinc/gpu_list.php

Quickmag shows Mag for RX 570
        Project Name|   Top 5 magnitude(s) for RX 570
    Amicable Numbers|    24.0    13.7    11.4     8.8     8.0
       Milkyway@home|    18.2    17.9    15.9    15.0    13.9
              Srbase|    35.8    34.8    33.4    22.0     3.1
             Gpugrid|     0.0    NULL    NULL    NULL    NULL
      **Asteroids@home|    69.5    40.0    29.7    26.0    19.0**
      Minecraft@home|    NULL    NULL    NULL    NULL    NULL

**Comment by nexus-prime** [comment]
That mag is being produced from CPU workunits. Asteroids is one of the oddball projects that is viable as either a GPU or CPU project. Right now the project seems to be leaning slightly towards CPUs.

You can edit the whitelist file to change Asteroids to a CPU project to see how various CPUs are performing, but then your results will occasionally be thrown off by people running GPU WUs.
