### ISSUE TITLE
Probably four formula does not consider RAC decay

### ISSUE THREAD

**Issue by rakovskij-stanislav** [nexus-prime/QuickMag.jl#4]
Reference: https://boinc.berkeley.edu/trac/wiki/CreditStats#rac-decay

**Comment by nexus-prime** [comment]
Can confirm that the data being pulled from the projects is already corrected for rac-decay on a daily basis. In theory the code could be modified to account for further rac-decay since the last database update, but that would ignore any additional credits being gained.
